[phases.setup]
nixPkgs = ["nodejs_latest"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]
dependsOn = ["install"]

[variables]
NODE_ENV = "production"

[start]
cmd = "npm run start"
